config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match '/', to: 'static_pages#home', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/dashboard', to: 'players#dashboard', via: 'get'

  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:create]
  resources :players, only: [:index, :update, :create]

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_and_belongs_to_many :users

  def self.import_all_players
    players = HTTParty.get('http://www.fantasyfootballnerd.com/service/players/json/mv96pra5v766/').first.last

    players.each do |player|
      if player["active"] == "1"
        Player.create(
          name: player["displayName"],
          last_name: player["lname"],
          first_name: player["fname"],
          team: player["team"],
          position: player["position"],
          school: player["college"],
          nerd_id: player["playerId"],
          predicted_points: 0
        )
      end
    end
  end

  def self.update_predicted_points
    positions = ["QB","RB","WR","TE", "K"]

    positions.each do |position|
      response = HTTParty.get("http://www.fantasyfootballnerd.com/service/weekly-rankings/json/mv96pra5v766/#{position}")
      rankings = response["Rankings"]

      rankings.each do |player|
        nerd_id = player["playerId"]
        found_player = Player.find_by(nerd_id: nerd_id)
        points = player["standard"]
        found_player.update(predicted_points: points)
      end
    end
  end


  def self.school_names
    pluck(:school).uniq.reject(&:empty?)
  end

  # def add_favorites_by_id
  #   @player_ids = player.id
  #   @player_ids.each do |id|
  #     @user.players << Player.find(id)
  #   end
  # end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :players

  before_save { email.downcase! }
  before_create :create_remember_token
  after_create :send_welcome_message

  reserved_words = "--"

  validates :phone, length: { is: 10 }
  validates :name, presence: true, length: { maximum: 254 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 254 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :school, presence: true
  validates :password, presence: true, length: { minimum: 6 }



  has_secure_password


  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::MD5.hexdigest(token.to_s)
  end

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end

  def send_welcome_message
    unless self.phone == "9999999999"
      account_sid = "AC411dc2b8d69e4ffa1b5ec193a8c8cd94"
      auth_token = "71061710dc77ac139f1b9c0cd0170cde"
      client = Twilio::REST::Client.new account_sid, auth_token

      from = "+12392014618" # My Twilio number

      client.account.messages.create(
        :from => from,
        :to => self.phone,
        :body => "Hey #{self.name}, Welcome to CollegePros! Go #{self.school}!"
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @user = current_user
    @players = Player.where(school: @user.school)
  end

  def create
    @user = current_user
    params[:favorites]["player_nerd_ids"].each do |id|
      @user.players << Player.find_by(nerd_id: id)
    end
    redirect_to dashboard_path
  end

  def dashboard
    @user = current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_back_or(dashboard_path(user))
    else
      flash[:danger] = "Sorry! Try signing in again!"
      redirect_to root_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to dashboard_path if signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:home]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
    @school_options = Player.school_names.sort
    @school_options.shift
  end

  def create
    @user = User.new(user_params)
    @school_options = Player.school_names.sort
    @school_options.shift
    if @user.save
      sign_in(@user)
      flash[:success] = "All signed up!  Go ahead and select the players you want to follow!"
      redirect_back_or players_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email,
        :password, :password_confirmation, :school, :phone)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    #save a cookie on their computer
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    #update our db with their cookie info
    user.update_attribute(:remember_token, User.digest(remember_token))
    #set a current_user variable equl to user
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?
    current_user == user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    if current_user != nil
      current_user.update_attribute(:remember_token,
                    User.digest(User.new_remember_token))
      #delete the cookie on their computer
      cookies.delete(:remember_token)
      #delete any record of a cookie in our database
      self.current_user = nil
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= '/'>CollegePros</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <% if signed_in? %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Dashboard", dashboard_path, method: "get" %></li>
              <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
            </ul>
          </li>
    <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collegepros</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class = "navigation">
    <%= render 'layouts/navigation' %>
  </div>

  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key} no-margin") %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/players/dashboard.html.erb
<title>CPros | Dashboard</title>

<div class = "player-table">
  <table class="table table-striped info">
    <tr>
      <th>Player</th>
      <th>Team</th>
      <th>Position</th>
      <th>Predicted Fantasy Points</th>
    </tr>
    <% @user.players.each do |favorite_player| %>
      <tr>
        <td><%= favorite_player.name %></td>
        <td><%= favorite_player.team %></td>
        <td><%= favorite_player.position %></td>
        <td><%= favorite_player.predicted_points %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/players/index.html.erb
<title>CPros | Players</title>
<h1>Follow Players from <%= @user.school %></h1>

<%= form_for(player_path(@user)) do |form| %>

  <!-- sort players by fantasy projected points for the season or next week -->
  <div class = "player-table">
    <table class="table table-striped info">
      <tr>
        <th>Follow</th>
        <th>Player</th>
        <th>Team</th>
        <th>Position</th>
      </tr>
    <% @players.each do |player| %>
      <tr>
        <td>
          <%= check_box_tag 'favorites[player_nerd_ids][]', player.nerd_id, @user.players.include?(player) %>
          <%= label_tag(:favorite, "Favorite") %>
        </td>
        <td><%= player.name %></td>
        <td><%= player.team%></td>
        <td><%= player.position %></td>
      </tr>
    <% end %>
    </table>
  <% end %>

<%= button_tag(type: 'submit', class: "btn btn-primary done_button") do %>
  <i class="icon-ok icon-white"></i> Done
<% end %>

</br>
</br>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="background">
  <img src="https://farm4.staticflickr.com/3211/2814168011_e6bb69cc9e_o.jpg" width="1500" height="1125" alt="IMG_1913"></a>
</div>

<title>CPros | Home</title>
<div class="container-fluid">
  <div class="row">
    <div class="welcome_text jumbotron hidden-xs col-sm-6 col-md-6 col-lg-8">
      <h1><span class = "welcome_header">Welcome to CollegePros</span></h1>
      <p>Follow your favorite college football stars in the pros.  See their stats for the current season and where they rank at their position amongst current NFL players.</p>
    </div>
    <div class="sign_in_box jumbotron col-xs-12 col-sm-2 col-md-2 col-lg-2">
      <p>Sign In</p>
      <div class="label_input">
        <%= render 'sessions/form' %>
      </div>
      <p>_______________________</p>
      <p>Don't have an account?</p>
      <a class="btn btn-primary btn-lg sign_up_button" role="button" href="/signup">Sign Up</a></br>
    </div>
    </div>
  </div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

<div class="signup-error-box text-left">
  <%= render 'shared/error_messages', object: f.object %>
</div>

  <div class="row">
    <div class="sign-up-label col-xs-12">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control input-sm", autofocus: true %>
      </br>

      <%= f.label :email, class: "control-label" %>
      <%= f.text_field :email, class: "form-control input-sm" %>
      </br>

      <%= f.label :password, "Password (6 characters)", class: "control-label" %>
      <%= f.password_field :password, class: "form-control input-sm" %>
      </br>

      <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
      <%= f.password_field :password_confirmation, class: "form-control input-sm" %>
      </br>

      <%= f.label :phone, "Phone Number", class: "control-label" %>
      <%= f.telephone_field :phone, class: "form-control input-sm" %>
     </br>

      <%= f.label :school, "Pick Your School"%>

      <%= f.select(:school, options_for_select(@school_options)) %></br></br></br>
    </div>
  </div>

  <div class="text-center done-button">
    <%= f.submit 'Done', class: "btn btn-lg btn-primary done_button" %>
  </div>
<% end %>

app/views/users/new.html.erb
<title>CPros | Sign Up</title>

<!-- <div class="background">
  <img src="https://farm4.staticflickr.com/3657/3463622733_fd8dbf8b3b_o.jpg" width="2300" height="845" alt="University of Alabama Bryant-Denny Stadium Panorama">
</div> -->
<!--
<div class="sign_up_box jumbotron">
  <div class ="sign_up_text">
    <h1>Sign Up</h1>
  </div>
  <div class="label_input">
    <%# render 'users/form' %>
  </div>
</div>

 -->

<div class="background">
  <img src="https://farm4.staticflickr.com/3657/3463622733_fd8dbf8b3b_o.jpg" width="2300" height="845" alt="University of Alabama Bryant-Denny Stadium Panorama">
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="jumbotron text-center">
      <h1>Sign Up</h1>
      <%= render 'users/form' %>
    </div>
  </div>
</div>